---
# Source: goodtribes/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: goodtribes
---
# Source: goodtribes/templates/ghcr-pull-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: goodtribes
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJUbWxyYkdGelIzVnVibUZ6T21kb2IxOWlaVlpWZEd0cVVITmtaREZWU1ZCMlUxUXdkRWRYU0dwbVdrMWpaell3TjJ4RU4xST0ifX19
---
# Source: goodtribes/templates/meilisearch-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goodtribes-meilisearch
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: goodtribes/templates/minio-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goodtribes-minio
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# Source: goodtribes/templates/postgres-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goodtribes-postgres
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: goodtribes/templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: goodtribes-backend
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
spec:
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: goodtribes
  ports:
    - port: 1337
      targetPort: 1337
---
# Source: goodtribes/templates/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: goodtribes-frontend
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
spec:
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: goodtribes
  ports:
    - port: 3000
      targetPort: 3000
---
# Source: goodtribes/templates/meilisearch-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: goodtribes-meilisearch
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
spec:
  selector:
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/part-of: goodtribes
  ports:
    - port: 7700
      targetPort: 7700
---
# Source: goodtribes/templates/minio-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: goodtribes-minio
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
spec:
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: goodtribes
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
---
# Source: goodtribes/templates/postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: goodtribes-postgres
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
spec:
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: goodtribes
  ports:
    - port: 5432
      targetPort: 5432
---
# Source: goodtribes/templates/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodtribes-backend
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
    app.kubernetes.io/name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/part-of: goodtribes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/part-of: goodtribes
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: backend
          image: "ghcr.io/goodtribes-org/goodtribes.org/backend:5468fd6e70cbc76e7400e05de0482512984d984c"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1337
              protocol: TCP
          envFrom:
            - secretRef:
                name: goodtribes-secret
          env:
            - name: DATABASE_CLIENT
              value: "postgres"
            - name: DATABASE_HOST
              value: "goodtribes-postgres"
            - name: DATABASE_NAME
              value: "goodtribes"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_SSL
              value: "false"
            - name: DATABASE_USERNAME
              value: "goodtribes"
            - name: HOST
              value: "0.0.0.0"
            - name: MEILI_HOST
              value: "http://goodtribes-meilisearch:7700"
            - name: PORT
              value: "1337"
          readinessProbe:
            httpGet:
              path: /_health
              port: 1337
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_health
              port: 1337
            initialDelaySeconds: 30
            periodSeconds: 30
---
# Source: goodtribes/templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodtribes-frontend
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
    app.kubernetes.io/name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/part-of: goodtribes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: goodtribes
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: frontend
          image: "ghcr.io/goodtribes-org/goodtribes.org/frontend:5468fd6e70cbc76e7400e05de0482512984d984c"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: goodtribes-secret
          env:
            - name: NEXT_PUBLIC_MEILI_HOST
              value: "http://goodtribes-meilisearch:7700"
            - name: NEXT_PUBLIC_STORAGE_URL
              value: "https://goodtribes.org/storage"
            - name: NEXT_PUBLIC_STRAPI_URL
              value: "http://goodtribes-backend:1337"
            - name: S3_ENDPOINT
              value: "http://goodtribes-minio:9000"
            - name: S3_PRIVATE_BUCKET
              value: "goodtribes-private"
            - name: S3_PUBLIC_BUCKET
              value: "goodtribes-public"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
---
# Source: goodtribes/templates/meilisearch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodtribes-meilisearch
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
    app.kubernetes.io/name: meilisearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: meilisearch
      app.kubernetes.io/part-of: goodtribes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meilisearch
        app.kubernetes.io/part-of: goodtribes
    spec:
      containers:
        - name: meilisearch
          image: "getmeili/meilisearch:v1.6"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7700
              protocol: TCP
          envFrom:
            - secretRef:
                name: goodtribes-secret
          env:
            - name: MEILI_ENV
              value: "production"
          volumeMounts:
            - name: meili-data
              mountPath: /meili_data
          readinessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: meili-data
          persistentVolumeClaim:
            claimName: goodtribes-meilisearch
---
# Source: goodtribes/templates/minio-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodtribes-minio
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
    app.kubernetes.io/name: minio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/part-of: goodtribes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/part-of: goodtribes
    spec:
      containers:
        - name: minio
          image: "minio/minio:latest"
          imagePullPolicy: IfNotPresent
          command: ["minio", "server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          envFrom:
            - secretRef:
                name: goodtribes-secret
          env:
          volumeMounts:
            - name: minio-data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: goodtribes-minio
---
# Source: goodtribes/templates/postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodtribes-postgres
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
    app.kubernetes.io/name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: goodtribes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: goodtribes
    spec:
      containers:
        - name: postgres
          image: "postgres:16-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: goodtribes-secret
          env:
            - name: POSTGRES_DB
              value: "goodtribes"
            - name: POSTGRES_USER
              value: "goodtribes"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - goodtribes
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - goodtribes
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: goodtribes-postgres
---
# Source: goodtribes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goodtribes-ingress
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: http
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
spec:
  ingressClassName: traefik
  rules:
    - host: goodtribes.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goodtribes-frontend
                port:
                  number: 3000
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: goodtribes-backend
                port:
                  number: 1337
    - host: www.goodtribes.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goodtribes-frontend
                port:
                  number: 3000
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: goodtribes-backend
                port:
                  number: 1337
  tls:
    - hosts:
      - goodtribes.org
      - www.goodtribes.org
      secretName: goodtribes-tls
---
# Source: goodtribes/templates/minio-init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: goodtribes-minio-init
  namespace: goodtribes
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: goodtribes
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: minio-init
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              mc alias set local http://goodtribes-minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
              mc mb --ignore-existing local/goodtribes-public
              mc mb --ignore-existing local/goodtribes-private
              mc anonymous set public local/goodtribes-public
          envFrom:
            - secretRef:
                name: goodtribes-secret
